# debuntu_jvm_polyglot-as_install
debuntu_database_postgresql_install_9.2
debuntu_database_postgresql_add_superuser polyglot-as
debuntu_ruby_rbenv_prepare-system
debuntu_invoke_as_user polyglot-as debuntu_rails-server_setup-as-polyglot-as
