debuntu_torquebox_install_3.0.1
debuntu_database_postgresql_install_9.2
debuntu_database_postgresql_add_superuser torquebox
debuntu_ruby_rbenv_prepare_system
debuntu_invoke_as_user torquebox debuntu_rails-server_setup-as-torquebox
