echo "ADDING SUPERUSER $1 TO POSTGRES"
PG_USER=$1
cat << HEREDOC0 | su -l postgres -c psql
CREATE USER "$PG_USER" superuser createdb login;
ALTER USER "$PG_USER" WITH PASSWORD '$PG_USER';
CREATE DATABASE "$PG_USER" ;
GRANT ALL ON DATABASE "$PG_USER" TO "$PG_USER";
HEREDOC0
